export const services=[
 {slug:"cham-soc-me-sau-sinh",tag:"Sau sinh",title:"Chăm sóc mẹ tại nhà",description:"Hỗ trợ các việc sinh hoạt và thư giãn đã thống nhất, trong không gian riêng của gia đình.",detail:"Phạm vi, thời lượng, chống chỉ định và chi phí phải được xác nhận trước mỗi lịch.",forWho:"Gia đình cần thêm người hỗ trợ các sinh hoạt thường ngày trong giai đoạn mẹ hồi phục.",includes:["Trao đổi tình trạng và nhu cầu trước buổi hẹn","Thống nhất danh sách việc hỗ trợ tại nhà","Ghi nhận phản hồi sau buổi chăm sóc"],notIncludes:["Khám, chẩn đoán hoặc kê đơn","Can thiệp y khoa và xử lý cấp cứu","Cam kết kết quả sức khỏe"]},
 {slug:"huong-dan-cham-be",tag:"Em bé",title:"Hướng dẫn chăm bé",description:"Chuyên viên thao tác mẫu và hướng dẫn người chăm cùng thực hành theo nhịp của bé.",detail:"Nội dung không thay thế tư vấn của bác sĩ, điều dưỡng hoặc hộ sinh.",forWho:"Người chăm muốn được hướng dẫn từng thao tác cơ bản và thực hành ngay tại nhà.",includes:["Khảo sát thói quen chăm bé của gia đình","Thao tác mẫu trong phạm vi đã thống nhất","Để người chăm thực hành và đặt câu hỏi"],notIncludes:["Đánh giá bệnh lý","Thay đổi chỉ định của nhân viên y tế","Xử lý dấu hiệu bất thường"]},
 {slug:"dong-hanh-thang-dau",tag:"Gia đình",title:"Đồng hành tháng đầu",description:"Lên lịch nhiều buổi với nội dung được điều chỉnh sau mỗi lần trao đổi cùng gia đình.",detail:"Số buổi, người phụ trách và điều kiện đổi lịch cần được ghi rõ bằng văn bản.",forWho:"Gia đình muốn có lịch hỗ trợ nhiều buổi thay vì đặt rời rạc từng lần.",includes:["Lập lịch dự kiến theo tuần","Giữ hồ sơ nhu cầu xuyên suốt các buổi","Rà soát lại phạm vi sau mỗi lần gặp"],notIncludes:["Trực tại nhà 24/7","Dịch vụ điều dưỡng hoặc hộ sinh","Cam kết một chuyên viên khi chưa xác nhận lịch"]}
];
export const articles=[
 {slug:"chuan-bi-truoc-buoi-cham-soc",title:"Chuẩn bị gì trước buổi chăm sóc tại nhà?",description:"Danh sách ngắn để gia đình chủ động không gian, câu hỏi và thông tin cần trao đổi."},
 {slug:"phan-biet-ho-tro-cham-soc-va-y-te",title:"Phân biệt hỗ trợ chăm sóc và dịch vụ y tế",description:"Những ranh giới cần hỏi rõ để không đặt kỳ vọng sai cho chuyên viên chăm sóc."},
 {slug:"bon-cau-hoi-truoc-khi-dat-lich",title:"Bốn câu hỏi trước khi đặt lịch",description:"Hỏi về người thực hiện, phạm vi, chi phí và cách xử lý khi cần đổi lịch."}
];
